### ISSUE TITLE
Bloodstem bandage counts as medicine for surgery

### ISSUE THREAD

**Issue by ghost** [B-Knight49/Rimworld-MedicalOverhaul#16] opened 2018-07-11 16:47 UTC
As seen in the image, when queuing an operation bill, the info message (top) notes:
> Operation requires **bloodstem bandage** or better

Is this intended behavior?  It seems bloodstem bandages have a medical potency of 20%.  I can imagine it being used for (painful) surgery, but it seems weird to use it to anesthetize pawns.

![20180711124546_1](https://user-images.githubusercontent.com/27655938/42587347-6c0c6eb0-8508-11e8-8c6a-376c47471897.jpg)

**Comment by I-Knight-I** [comment] 2018-07-11 18:52
This is caused by Bloodstem Bandages inheriting from the "Medicine" C# class. In other words, it shares the same code as Herbal Medicine and just Medicine - both of which can be used to anaesthetise pawns. I'll probably have to make it use its own class which means copying the code from "Medicine" and removing the part which allows it to be used as an anaesthetic.

**Comment by ghost** [comment] 2018-07-11 20:03
The PR #18 will prevent pawns from using bloodstem bandages for surgery.  However, the message will still mention
> Operation requires bloodstem bandage or better

if the recipient pawn has medicine disabled.

**Comment by I-Knight-I** [comment] 2018-07-28 15:27
Pretty sure this'd count as a full bug fix. Going to move this to "Done" and close it unless further work is needed.

**Closed as completed by I-Knight-I** 2018-07-28 15:27 UTC
Labels: Bug, Done
